import { Injectable, Logger, BadRequestException, Inject, forwardRef } from '@nestjs/common';
import { AiClient } from '../gemini/ai.client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { 
  SECTION_PLANNER_SYSTEM, 
  SECTION_PLANNER_PROMPT, 
  WIDGET_GENERATOR_SYSTEM, 
  WIDGET_GENERATOR_PROMPT 
} from '../gemini/prompts/templates.js';
import { RagService } from './rag.service.js';
import { GuardrailService } from './guardrail.service.js';
import { ConfigService } from '@nestjs/config';

export interface GeneratedWidget {
  type: string;
  contentConfig?: Record<string, unknown>;
  sortOrder: number;
}

export interface GeneratedPage {
  title: string;
  slug: string;
  widgets?: GeneratedWidget[];
}

export interface GeneratedSite {
  site: {
    name: string;
    subdomain: string;
  };
  pages: GeneratedPage[];
  projectId?: string;
  screenId?: string;
  htmlUrl?: string;
  imageUrl?: string;
  generationMode?: 'stitch' | 'hybrid';
}

interface ReflectionResult {
  passed: boolean;
  feedback?: string;
}

const PM_SYSTEM_INSTRUCTION = `You are an expert Product Manager and UX Designer for Genzite. 
Your job is to take a user's brief request and expand it into a highly detailed, professional UI design prompt.
MANDATORY: You MUST design a complete, production-ready, fully responsive landing page.
MANDATORY SECTIONS: Header, Hero, Features, Testimonials, Pricing, FAQ, CTA, and Footer.
AESTHETICS: Use premium design, glassmorphism, dynamic gradients, modern typography, and interactive states. Do NOT output wireframes or placeholders.
Ensure the design is SEO-friendly (semantic HTML5 sections, proper heading hierarchy, descriptive alt text).

CRITICAL REQUIREMENT - You MUST append this EXACT Design System block to the very bottom of your output prompt:
**DESIGN SYSTEM (REQUIRED):**
- **Frameworks:** React (Function Components), Tailwind CSS v4, Lucide React (icons), Framer Motion (animations).
- **Theme:** Dark mode by default (Backgrounds: #09090b, #0f172a, #111827).
- **Typography:** 'Inter' font for everything. Use semantic sizes (text-sm, text-base, text-2xl, etc.).
- **Colors:** Use Slate/Zinc for neutrals. Primary accent should be Cyan/Emerald gradient or #06B6D4. No Purple/Violet.
- **Components:** Use shadcn-like clean components with rounded corners (rounded-xl, rounded-2xl).
- **Interactive:** Add hover effects (hover:scale-105, hover:bg-white/10), smooth transitions (transition-all duration-300).
- **Output:** MUST use semantic HTML5 elements. MUST NOT use generic HTML tables for layouts.

Do NOT generate code yourself. Only generate the descriptive prompt including the required Design System block.`;

const AUDITOR_SYSTEM_INSTRUCTION = `You are a strict UX/UI QA Auditor and Security Expert. 
Your job is to review HTML/Tailwind code to ensure it meets high standards of accessibility, visual hierarchy, usability, and prevents XSS or other vulnerabilities.
Return JSON strictly in this format: { "passed": boolean, "feedback": "string explaining what needs to be fixed if passed is false" }`;

const WIDGET_EXTRACTOR_INSTRUCTION = `You are an expert Frontend Architect.
Your job is to read raw HTML generated by a design tool and convert it into a structured JSON array of widgets for the Genzite Canvas Builder.
Supported Widget Types: HEADER, HERO, TEXT, FEATURELIST, IMAGEGALLERY, TESTIMONIAL, STATS, CTA, FOOTER, PRICING, FAQ, CONTACT.
Return the result strictly as a JSON object containing a "site" and "pages" array.
CRITICAL STYLING INSTRUCTION: You MUST extract CSS styling attributes from the HTML (colors, padding, borders) and inject them into each widget's contentConfig.
- bgColor: Extract background colors (e.g., "#0f172a", "rgba(0,0,0,0.5)", or gradient).
- textColor: Extract primary text color.
- padding: Extract section padding (e.g., "80px 24px").
- borderRadius: Extract border radius (e.g., "16px").
Example Output:
{
  "site": { "name": "Generated Site", "subdomain": "site-xyz" },
  "pages": [
    {
      "title": "Home",
      "slug": "home",
      "widgets": [
        { "type": "HEADER", "contentConfig": { "title": "Logo", "items": [{ "text": "Home" }], "bgColor": "#000000", "padding": "16px 24px" } },
        { "type": "HERO", "contentConfig": { "title": "Welcome", "ctaText": "Click here", "bgColor": "linear-gradient(to right, #000, #333)", "textColor": "#ffffff", "borderRadius": "24px" } }
      ]
    }
  ]
}
Ensure all content and extracted styling from the HTML is accurately represented in the widgets' contentConfig.`;

import { ToolRegistry } from '../agent/tools/tool.registry.js';

@Injectable()
export class SiteGeneratorService {
  private readonly logger = new Logger(SiteGeneratorService.name);

  constructor(
    private readonly ai: AiClient,
    private readonly prisma: PrismaService,
    private readonly rag: RagService,
    private readonly guardrail: GuardrailService,
    private readonly config: ConfigService,
    @Inject(forwardRef(() => ToolRegistry))
    private readonly toolRegistry: ToolRegistry,
  ) { }

  async generate(
    prompt: string,
    userId?: string,
    model?: string,
    siteId?: string,
    onProgress?: (step: string, percent: number) => void
  ): Promise<GeneratedSite> {
    // STEP 0: Security Check (Guardrail)
    onProgress?.('Security check...', 10);
    const guardrailCheck = await this.guardrail.checkPrompt(prompt);
    if (!guardrailCheck.isSafe) {
      throw new BadRequestException(`Request rejected: ${guardrailCheck.reason || 'Inappropriate content.'}`);
    }

    const taskLog = await this.prisma.aiTaskLog.create({
      data: {
        userId: userId ?? 'anonymous',
        taskType: 'SITE_GENERATION',
        input: { prompt, model } as object,
        startedAt: new Date(),
      },
    });

    try {
      // STEP 1: Parallelize RAG - Extract Golden Template from Database
      onProgress?.('Initializing generation...', 15);
      const [goldenTemplate] = await Promise.all([
        this.rag.retrieveTemplate(prompt)
      ]);

      const genMode = this.config.get<string>('GENERATION_MODE')?.replace(/['"]/g, '') || 'stitch';
      this.logger.log(`Current GENERATION_MODE from config: ${this.config.get<string>('GENERATION_MODE')} -> Parsed: ${genMode}`);

      if (genMode === 'hybrid') {
        return await this.generateHybrid(prompt, taskLog, siteId, onProgress);
      }

      // --- STITCH MODE (LEGACY) ---
      const pmPrompt = `User request: "${prompt}"\n\nReference Structure:\n${goldenTemplate}\n\nPlease write a highly detailed design prompt based on this request.`;

      // STEP 2: PM (Gemini) writes refined prompt
      onProgress?.('Product Manager is drafting design spec...', 30);
      
      const refinedPrompt = await this.ai.generateContent(pmPrompt, {
        model: model as any,
        systemInstruction: PM_SYSTEM_INSTRUCTION,
        temperature: 0.7,
        tools: this.toolRegistry.getDeclarations(), // Allow Gemini to use MCP tools if it needs to check codebase
      });

      this.logger.log(`Refined Prompt: ${refinedPrompt.substring(0, 100)}...`);

      // STEP 3: Designer (Stitch SDK) generates UI
      onProgress?.('Designer (Stitch) is drawing UI...', 50);
      const { stitch } = await import('@google/stitch-sdk');
      const apiKey = this.config.get<string>('STITCH_API_KEY') || this.config.get<string>('GEMINI_API_KEY');
      if (apiKey) {
        process.env.STITCH_API_KEY = apiKey;
      }
      const project = await stitch.createProject(`Genzite_${Date.now()}`);
      this.logger.log(`Created Stitch Project: ${project.id}`);

      let screen = await project.generate(refinedPrompt);
      this.logger.log(`Generated Screen: ${screen.id}`);

      let [htmlUrl, imageUrl] = await Promise.all([
        screen.getHtml(),
        screen.getImage()
      ]);

      let attempt = 1;
      const MAX_ATTEMPTS = 1; // Giới hạn 1 vòng lặp để tiết kiệm Quota API Gemini
      let htmlContent = '';

      while (attempt <= MAX_ATTEMPTS) {
        // Fetch HTML from Stitch for QA auditing with error handling
        try {
          if (!htmlUrl) throw new Error("Stitch returned empty HTML URL");
          const res = await fetch(htmlUrl);
          if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
          htmlContent = await res.text();
        } catch (err) {
          this.logger.warn(`[Attempt ${attempt}] Failed to fetch HTML from ${htmlUrl}: ${err}`);
          htmlContent = '<!-- Failed to load HTML -->';
        }

        // STEP 4: QA (Groq Llama 3) reviews HTML
        onProgress?.(attempt === 1 ? 'QA Expert is reviewing code...' : 'QA Expert is re-reviewing code...', 70 + attempt * 10);
        this.logger.log(`[Attempt ${attempt}] Calling QA (Groq)...`);

        const auditorPrompt = `Review this generated HTML/Tailwind for UX/UI issues:\n\n\`\`\`html\n${htmlContent.substring(0, 3000)}...\n\`\`\``;

        const reflection = await this.ai.generateJson<ReflectionResult>(auditorPrompt, {
          model: 'meta/llama-3.3-70b-instruct', // Force NVIDIA NIM for speed and accuracy
          systemInstruction: AUDITOR_SYSTEM_INSTRUCTION,
          temperature: 0.1,
        });

        if (reflection.passed) {
          this.logger.log(`[Attempt ${attempt}] QA passed!`);
          break;
        } else {
          this.logger.warn(`[Attempt ${attempt}] QA rejected: ${reflection.feedback}`);
          if (attempt === MAX_ATTEMPTS) {
            this.logger.warn(`Max attempts reached. Accepting current design.`);
            break;
          }

          // STEP 5: Correction loop (Edit)
          onProgress?.('Designer (Stitch) is fixing issues...', 85);
          this.logger.log(`Sending feedback to Stitch for edit...`);

          const editPrompt = `${refinedPrompt}\n\nIMPORTANT FEEDBACK TO FIX: ${reflection.feedback}`;
          screen = await project.generate(editPrompt);

          let newUrls = await Promise.all([
            screen.getHtml(),
            screen.getImage()
          ]);
          htmlUrl = newUrls[0];
          imageUrl = newUrls[1];

          attempt++;
        }
      }

      // STEP 6: Bypass Widget Extraction for GrapesJS
      onProgress?.('Preparing visual editor...', 90);
      this.logger.log(`Skipping JSON extraction, saving raw HTML for GrapesJS...`);
      
      const extractionResult = {
        site: { name: "Generated Site", subdomain: siteId || `gen-${Date.now()}` },
        pages: [{
          title: "Home",
          slug: "home",
          widgets: [{ 
            type: "GRAPESJS", 
            contentConfig: { html: htmlContent },
            sortOrder: 1
          }]
        }]
      };

      if (siteId) {
        extractionResult.site['id'] = siteId;
      }

      const result: GeneratedSite = {
        projectId: project.id,
        screenId: screen.id,
        htmlUrl,
        imageUrl,
        site: extractionResult.site,
        pages: extractionResult.pages,
      };

      await this.prisma.aiTaskLog.update({
        where: { id: taskLog.id },
        data: {
          status: 'COMPLETED',
          output: result as unknown as object,
          endedAt: new Date(),
        },
      });

      onProgress?.('Completed!', 100);
      this.logger.log(`Site generation finalized.`);
      return result;
    } catch (error) {
      await this.prisma.aiTaskLog.update({
        where: { id: taskLog.id },
        data: {
          status: 'FAILED',
          error: error instanceof Error ? error.message : 'Unknown error',
          endedAt: new Date(),
        },
      });
      throw error;
    }
  }

  private async generateHybrid(
    prompt: string,
    taskLog: any,
    siteId?: string,
    onProgress?: (step: string, percent: number) => void
  ): Promise<GeneratedSite> {
    try {
      this.logger.log('Starting HYBRID parallel generation mode');
      onProgress?.('Planner is analyzing sections...', 20);

      // STEP 1: Plan Sections
      const planPrompt = SECTION_PLANNER_PROMPT.replace('{{PROMPT}}', prompt);
      const planResult = await this.ai.generateJson<{ sections: any[] }>(planPrompt, {
        model: 'gemini-2.0-flash',
        systemInstruction: SECTION_PLANNER_SYSTEM,
      });

      const sections = planResult.sections || [];
      this.logger.log(`Planned ${sections.length} sections for parallel generation`);

      // STAGE 1: Split Sections
      const stitchSections = sections.filter(sec => sec.assignTo === 'stitch' || sec.type === 'HEADER' || sec.type === 'HERO');
      const llmSections = sections.filter(sec => !(sec.assignTo === 'stitch' || sec.type === 'HEADER' || sec.type === 'HERO'));

      onProgress?.('Generating primary design (Stitch)...', 30);

      // STAGE 1: Execute Stitch Workers
      const stitchPromises = stitchSections.map(async (sec) => {
        // Fallback to Stitch for Header/Hero
        const { stitch } = await import('@google/stitch-sdk');
        const apiKey = this.config.get<string>('STITCH_API_KEY') || this.config.get<string>('GEMINI_API_KEY');
        if (apiKey) process.env.STITCH_API_KEY = apiKey;
        const project = await stitch.createProject(`Genzite_Part_${Date.now()}`);
        const screen = await project.generate(`Design a ${sec.type} section. ${sec.briefing}`);
        const htmlUrl = await screen.getHtml();
        
        let htmlContent = '';
        try {
          const res = await fetch(htmlUrl);
          htmlContent = await res.text();
        } catch (e) {
          htmlContent = '<!-- Failed to fetch -->';
        }
        
        const extractionResult = await this.ai.generateJson<any>(
          `Convert this HTML to JSON widget format:\n${htmlContent.substring(0, 10000)}`, 
          { model: 'meta/llama-3.3-70b-instruct', systemInstruction: WIDGET_EXTRACTOR_INSTRUCTION }
        );
        
        return {
          type: sec.type,
          sortOrder: sec.sortOrder,
          contentConfig: extractionResult?.pages?.[0]?.widgets?.[0]?.contentConfig || { title: sec.type }
        };
      });

      const stitchWidgets = await Promise.all(stitchPromises);

      // Extract colors from Stitch to build Dynamic Design Tokens
      let extractedBg = "var(--gz-dark-1)";
      let extractedText = "var(--color-text-primary)";
      
      const heroWidget = stitchWidgets.find(w => w.type === 'HERO') || stitchWidgets[0];
      if (heroWidget?.contentConfig?.bgColor) {
         extractedBg = heroWidget.contentConfig.bgColor;
      }
      if (heroWidget?.contentConfig?.textColor) {
         extractedText = heroWidget.contentConfig.textColor;
      }

      // DYNAMIC DESIGN TOKENS
      const DESIGN_TOKENS = `
        MANDATORY: You MUST ONLY use valid Tailwind CSS classes. Do NOT use string interpolation like \`\${...}\` or raw CSS variables like \`var(...)\` in class names.
        Use the following custom Tailwind theme values:
        - Background Colors: bg-surface-container-lowest, bg-surface-container, bg-surface-container-high
        - Text Colors: text-on-surface (for headings), text-on-surface-variant (for body)
        - Accent Colors: text-primary, bg-primary
        - Padding: p-6, py-12, px-4
        - Border Radius: rounded-xl, rounded-2xl
      `;

      onProgress?.('Workers are building sections to match theme...', 60);

      const runLlmWorker = async (sec: any) => {
        const workerPrompt = WIDGET_GENERATOR_PROMPT
          .replace('{{SECTION_TYPE}}', sec.type)
          .replace('{{BRIEFING}}', sec.briefing)
          .replace('{{DESIGN_TOKENS}}', DESIGN_TOKENS);
          
        let modelName = 'deepseek-chat';
        if (sec.assignTo === 'nvidia') modelName = 'meta/llama-3.3-70b-instruct';
        if (sec.assignTo === 'groq') modelName = 'llama-3.3-70b-versatile';
        if (sec.assignTo === 'deepseek') modelName = 'deepseek-ai/deepseek-v4-flash';
        
        try {
          const widgetResult = await this.ai.generateJson<{ html: string, css?: string }>(workerPrompt, {
            model: modelName as any,
            systemInstruction: WIDGET_GENERATOR_SYSTEM,
            temperature: 0.7
          });
          return {
            type: sec.type,
            sortOrder: sec.sortOrder,
            htmlContent: widgetResult.html || `<!-- Missing HTML for ${sec.type} -->`,
            cssContent: widgetResult.css || ''
          };
        } catch (e) {
          this.logger.warn(`Worker ${modelName} failed for ${sec.type}, falling back...`);
          const fallbackResult = await this.ai.generateJson<{ html: string, css?: string }>(workerPrompt, {
            model: 'meta/llama-3.3-70b-instruct',
            systemInstruction: WIDGET_GENERATOR_SYSTEM,
          });
          return {
            type: sec.type,
            sortOrder: sec.sortOrder,
            htmlContent: fallbackResult.html || `<!-- Missing HTML for ${sec.type} -->`,
            cssContent: fallbackResult.css || ''
          };
>>>>>>> main
        }
      };

      // STEP 2: Execute Parallel Workers
      const widgetPromises = sections.map(async (sec) => {
        if (sec.assignTo === 'stitch' || sec.type === 'HEADER' || sec.type === 'HERO') {
          try {
            // Fallback to Stitch for Header/Hero
            const { stitch } = await import('@google/stitch-sdk');
            const apiKey = this.config.get<string>('STITCH_API_KEY') || this.config.get<string>('GEMINI_API_KEY');
            if (apiKey) process.env.STITCH_API_KEY = apiKey;
            const project = await stitch.createProject(`Genzite_Part_${Date.now()}`);
            const screen = await project.generate(`Design a ${sec.type} section. ${sec.briefing}`);
            const htmlUrl = await screen.getHtml();
            
            if (!htmlUrl) throw new Error("Stitch returned empty HTML URL");
            const res = await fetch(htmlUrl);
            if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
            
            let rawHtml = await res.text();
            let parsedHtml = '';
            
            const styleRegex = /<style[^>]*>([\s\S]*?)<\/style>/gi;
            let match;
            while ((match = styleRegex.exec(rawHtml)) !== null) {
              parsedHtml += `<style>${match[1]}</style>\n`;
            }
            
            const bodyMatch = rawHtml.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
            if (bodyMatch && bodyMatch[1]) {
              parsedHtml += bodyMatch[1];
            } else {
              parsedHtml += rawHtml;
            }
            
            return {
              type: sec.type,
              sortOrder: sec.sortOrder,
              htmlContent: parsedHtml.trim(),
              cssContent: ''
            };
          } catch (e) {
            this.logger.warn(`Failed to fetch Stitch section ${sec.type}: ${e}. Falling back to LLM generation...`);
            return await runLlmWorker(sec);
          }
        } else {
          return await runLlmWorker(sec);
        }
      });

      const generatedWidgets = await Promise.all(widgetPromises);
      
      // Sort widgets
      generatedWidgets.sort((a, b) => a.sortOrder - b.sortOrder);
      
      const fullHtml = generatedWidgets.map(w => w.htmlContent).join('\n\n');
      const fullCss = generatedWidgets.map(w => w.cssContent).filter(css => !!css).join('\n\n');

      onProgress?.('Merging and finalizing UI...', 90);

      const generatedSubdomain = siteId ? siteId : `gen-${Date.now()}`;
      const result: GeneratedSite = {
        generationMode: 'hybrid',
        site: { name: "Hybrid Site", subdomain: generatedSubdomain, ...(siteId ? { id: siteId } : {}) },
        pages: [{
          title: "Home",
          slug: "home",
          widgets: [{
            type: "GRAPESJS",
            contentConfig: { html: fullHtml, css: fullCss },
            sortOrder: 1
          }]
        }]
      };

      await this.prisma.aiTaskLog.update({
        where: { id: taskLog.id },
        data: {
          status: 'COMPLETED',
          output: result as unknown as object,
          endedAt: new Date(),
        },
      });

      onProgress?.('Completed!', 100);
      this.logger.log(`Hybrid generation finalized.`);
      return result;

    } catch (error) {
      await this.prisma.aiTaskLog.update({
        where: { id: taskLog.id },
        data: {
          status: 'FAILED',
          error: error instanceof Error ? error.message : 'Unknown error',
          endedAt: new Date(),
        },
      });
      throw error;
    }
  }
}
