import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import { AiClient } from '../gemini/ai.client.js';
import { PrismaService } from '../prisma/prisma.service.js';
import { RagService } from './rag.service.js';
import { GuardrailService } from './guardrail.service.js';
import { ConfigService } from '@nestjs/config';

export interface GeneratedSite {
  projectId: string;
  screenId: string;
  htmlUrl: string;
  imageUrl: string;
  site?: { name: string; subdomain: string };
  pages?: Array<{ title: string; slug: string; widgets: any[] }>;
}

interface ReflectionResult {
  passed: boolean;
  feedback?: string;
}

const PM_SYSTEM_INSTRUCTION = `You are an expert Product Manager and UX Designer. 
Your job is to take a user's brief request and expand it into a highly detailed, professional UI design prompt.
MANDATORY: You MUST design a complete, production-ready, fully responsive landing page.
MANDATORY SECTIONS: Header, Hero, Features, Testimonials, Pricing, FAQ, CTA, and Footer.
AESTHETICS: Use premium design, glassmorphism, dynamic gradients, modern typography, and interactive states. Do NOT output wireframes or placeholders.
Ensure the design is SEO-friendly (semantic HTML5 sections, proper heading hierarchy, descriptive alt text).
Do NOT generate code. Only generate the descriptive prompt.`;

const AUDITOR_SYSTEM_INSTRUCTION = `You are a strict UX/UI QA Auditor and Security Expert. 
Your job is to review HTML/Tailwind code to ensure it meets high standards of accessibility, visual hierarchy, usability, and prevents XSS or other vulnerabilities.
Return JSON strictly in this format: { "passed": boolean, "feedback": "string explaining what needs to be fixed if passed is false" }`;

const WIDGET_EXTRACTOR_INSTRUCTION = `You are an expert Frontend Architect.
Your job is to read raw HTML generated by a design tool and convert it into a structured JSON array of widgets for the Genzite Canvas Builder.
Supported Widget Types: HEADER, HERO, TEXT, FEATURELIST, IMAGEGALLERY, TESTIMONIAL, STATS, CTA, FOOTER.
Return the result strictly as a JSON object containing a "site" and "pages" array.
Example Output:
{
  "site": { "name": "Generated Site", "subdomain": "site-xyz" },
  "pages": [
    {
      "title": "Home",
      "slug": "home",
      "widgets": [
        { "type": "HEADER", "contentConfig": { "title": "Logo", "items": [{ "text": "Home" }] } },
        { "type": "HERO", "contentConfig": { "title": "Welcome", "subtitle": "Discover more", "ctaText": "Click here" } }
      ]
    }
  ]
}
Ensure all content from the HTML is accurately represented in the widgets' contentConfig.`;

@Injectable()
export class SiteGeneratorService {
  private readonly logger = new Logger(SiteGeneratorService.name);

  constructor(
    private readonly ai: AiClient,
    private readonly prisma: PrismaService,
    private readonly rag: RagService,
    private readonly guardrail: GuardrailService,
    private readonly config: ConfigService,
  ) { }

  async generate(
    prompt: string,
    userId?: string,
    model?: string,
    siteId?: string,
    onProgress?: (step: string, percent: number) => void
  ): Promise<GeneratedSite> {
    // STEP 0: Security Check (Guardrail)
    onProgress?.('Security check...', 10);
    const guardrailCheck = await this.guardrail.checkPrompt(prompt);
    if (!guardrailCheck.isSafe) {
      throw new BadRequestException(`Request rejected: ${guardrailCheck.reason || 'Inappropriate content.'}`);
    }

    const taskLog = await this.prisma.aiTaskLog.create({
      data: {
        userId: userId ?? 'anonymous',
        taskType: 'SITE_GENERATION',
        input: { prompt, model } as object,
        startedAt: new Date(),
      },
    });

    try {
      // STEP 1: Parallelize RAG - Extract Golden Template from Database
      onProgress?.('Initializing generation...', 15);
      const [goldenTemplate] = await Promise.all([
        this.rag.retrieveTemplate(prompt)
      ]);

      const pmPrompt = `User request: "${prompt}"\n\nReference Structure:\n${goldenTemplate}\n\nPlease write a highly detailed design prompt based on this request.`;

      // STEP 2: PM (Gemini) writes refined prompt
      onProgress?.('Product Manager is drafting design spec...', 30);
      const refinedPrompt = await this.ai.generateContent(pmPrompt, {
        model: model as any,
        systemInstruction: PM_SYSTEM_INSTRUCTION,
        temperature: 0.7,
      });

      this.logger.log(`Refined Prompt: ${refinedPrompt.substring(0, 100)}...`);

      // STEP 3: Designer (Stitch SDK) generates UI
      onProgress?.('Designer (Stitch) is drawing UI...', 50);
      const { stitch } = await import('@google/stitch-sdk');
      const apiKey = this.config.get<string>('STITCH_API_KEY') || this.config.get<string>('GEMINI_API_KEY');
      if (apiKey) {
        process.env.STITCH_API_KEY = apiKey;
      }
      const project = await stitch.createProject(`Genzite_${Date.now()}`);
      this.logger.log(`Created Stitch Project: ${project.id}`);

      let screen = await project.generate(refinedPrompt);
      this.logger.log(`Generated Screen: ${screen.id}`);

      let [htmlUrl, imageUrl] = await Promise.all([
        screen.getHtml(),
        screen.getImage()
      ]);

      let attempt = 1;
      const MAX_ATTEMPTS = 1; // Giới hạn 1 vòng lặp để tiết kiệm Quota API Gemini
      let htmlContent = '';

      while (attempt <= MAX_ATTEMPTS) {
        // Fetch HTML from Stitch for QA auditing with error handling
        try {
          const res = await fetch(htmlUrl);
          if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
          htmlContent = await res.text();
        } catch (err) {
          this.logger.warn(`[Attempt ${attempt}] Failed to fetch HTML from ${htmlUrl}: ${err}`);
          htmlContent = '<!-- Failed to load HTML -->';
        }

        // STEP 4: QA (Groq Llama 3) reviews HTML
        onProgress?.(attempt === 1 ? 'QA Expert is reviewing code...' : 'QA Expert is re-reviewing code...', 70 + attempt * 10);
        this.logger.log(`[Attempt ${attempt}] Calling QA (Groq)...`);

        const auditorPrompt = `Review this generated HTML/Tailwind for UX/UI issues:\n\n\`\`\`html\n${htmlContent.substring(0, 3000)}...\n\`\`\``;

        const reflection = await this.ai.generateJson<ReflectionResult>(auditorPrompt, {
          model: 'llama-3.3-70b-versatile', // Force Groq for speed
          systemInstruction: AUDITOR_SYSTEM_INSTRUCTION,
          temperature: 0.1,
        });

        if (reflection.passed) {
          this.logger.log(`[Attempt ${attempt}] QA passed!`);
          break;
        } else {
          this.logger.warn(`[Attempt ${attempt}] QA rejected: ${reflection.feedback}`);
          if (attempt === MAX_ATTEMPTS) {
            this.logger.warn(`Max attempts reached. Accepting current design.`);
            break;
          }

          // STEP 5: Correction loop (Edit)
          onProgress?.('Designer (Stitch) is fixing issues...', 85);
          this.logger.log(`Sending feedback to Stitch for edit...`);

          const editPrompt = `${refinedPrompt}\n\nIMPORTANT FEEDBACK TO FIX: ${reflection.feedback}`;
          screen = await project.generate(editPrompt);

          let newUrls = await Promise.all([
            screen.getHtml(),
            screen.getImage()
          ]);
          htmlUrl = newUrls[0];
          imageUrl = newUrls[1];

          attempt++;
        }
      }

      // STEP 6: Extract Widgets (AI Translation)
      onProgress?.('Extracting editable widgets...', 90);
      this.logger.log(`Calling AI to extract JSON widgets from HTML...`);
      
      const extractionPrompt = `Convert this HTML into Genzite Canvas JSON format:\n\n\`\`\`html\n${htmlContent.substring(0, 80000)}...\n\`\`\``;
      
      let extractionResult: any = { site: { name: "Generated", subdomain: `gen-${Date.now()}` }, pages: [] };
      try {
        extractionResult = await this.ai.generateJson<any>(extractionPrompt, {
          model: 'llama-3.3-70b-versatile', // Dùng Groq để xử lý JSON siêu tốc độ và tiết kiệm Gemini Quota
          systemInstruction: WIDGET_EXTRACTOR_INSTRUCTION,
          temperature: 0.2,
        });
        
        // Ensure subdomain is safe and unique or use existing siteId
        if (siteId) {
          extractionResult.site.id = siteId;
        } else if (extractionResult?.site) {
          extractionResult.site.subdomain = (extractionResult.site.subdomain || 'site').toLowerCase().replace(/[^a-z0-9-]/g, '') + '-' + Math.floor(Math.random() * 10000);
        }
      } catch (e) {
        this.logger.error(`Widget extraction failed: ${e}`);
        // Fallback to basic structure if extraction fails so the site doesn't crash downstream
        extractionResult = {
          site: { id: siteId, name: "Generated Site", subdomain: `gen-${Date.now()}` },
          pages: [{ title: "Home", slug: "home", widgets: [{ type: "HERO", contentConfig: { title: "Generated Site" } }] }]
        };
      }

      const result: GeneratedSite = {
        projectId: project.id,
        screenId: screen.id,
        htmlUrl,
        imageUrl,
        site: extractionResult.site,
        pages: extractionResult.pages,
      };

      await this.prisma.aiTaskLog.update({
        where: { id: taskLog.id },
        data: {
          status: 'COMPLETED',
          output: result as unknown as object,
          endedAt: new Date(),
        },
      });

      onProgress?.('Completed!', 100);
      this.logger.log(`Site generation finalized.`);
      return result;
    } catch (error) {
      await this.prisma.aiTaskLog.update({
        where: { id: taskLog.id },
        data: {
          status: 'FAILED',
          error: error instanceof Error ? error.message : 'Unknown error',
          endedAt: new Date(),
        },
      });
      throw error;
    }
  }
}
